development:
  adapter: postgresql
  encoding: unicode
  database: orienteering_development
  pool: 5
  host: localhost
  username: hawell
  password: 1234qwe1234

test:
  adapter: postgresql
  encoding: unicode
  database: orienteering_test
  pool: 5
  username: hawell
  password: 1234qwe1234

production:
  url: <%= ENV['DATABASE_URL'] %>
