# config/sidekiq.yml
:concurrency: 5  # Adjust the concurrency level based on your Heroku plan and Redis limits

:queues:
  - default
  - mailers
  - critical
  - low

:logging: true

# SSL configuration for Redis (useful when Redis requires SSL)
:redis:
  url: "rediss://:REDACTED@ec2-23-21-53-92.compute-1.amazonaws.com:24270"
  ssl_params:
    verify_mode: 0
